# 1. Numeric .. Logical .. Character

- Both Character and String are considered as Character class in R <br />
- Both integer and float both are considered as numeric class in R

In [37]:
i = 12
class(i)

[1] "numeric"

In [38]:
f = 3.1427
class(f)

[1] "numeric"

In [39]:
z = 'a'
class(z)

[1] "character"

In [40]:
z = 'aslam'
class(z)

[1] "character"

In [41]:
b= TRUE
class(b)

[1] "logical"

# 2. Vectors

- Vector can contain any kind of element but its class type will be determined by below and all elements will be converted to that data type. <br /> <br />
 **Hierarchy of Mixed Vectors**
1. Character
2. Numeric/Integer
3. Logical

In [42]:
mv1 = c(1.56, 1, 3)
print(mv1)
class(mv1)

[1] 1.56 1.00 3.00


[1] "numeric"

In [43]:
mv2 = c(1.56, 1, 3, TRUE)
print(mv2)
class(mv2)

[1] 1.56 1.00 3.00 1.00


[1] "numeric"

In [44]:
mv3 = c(1.56, 1, 3, "Test")
print(mv3)
class(mv3)

[1] "1.56" "1"    "3"    "Test"


[1] "character"

### 2.1 Structure of Vector

In [45]:
str(mv3)

 chr [1:4] "1.56" "1" "3" "Test"


### 2.2 Length of Vector

In [46]:
length(mv3)

[1] 4

### 2.3 Indexing Elements of Vector

In [47]:
vc1 = c(10,20,30,40,50,60,70,80,90,11,22,33,44,55,66,77,88,99)
length(vc1)

[1] 18

In [48]:
vc1[1]

[1] 10

In [49]:
vc1[3:8]

[1] 30 40 50 60 70 80

In [50]:
vc1[c(1,6,9,14)]

[1] 10 60 90 55

### 2.4 Drop Elements from Vector

In [51]:
# Drop element at 3 (Does not change the Original Vector)
vc1[-3]

[1] 10 20 40 50 60 70 80 90 11 22 33 44 55 66 77 88 99

In [52]:
# drop elements at 3 to 7 (Does not change the Original Vector)

vc1[-(3:7)]  #or vc1[-3:-7] 

[1] 10 20 80 90 11 22 33 44 55 66 77 88 99

### 2.5 Get Last element of Vector

In [53]:
vc1[length(vc1)]

[1] 99

In [54]:
# Get Last element of Vector by Tail method
tail(vc1, 1)

[1] 99

In [55]:
# Get last 3 Elements
vc1[ (length(vc1)-2) : length(vc1)]

[1] 77 88 99

In [56]:
# Get last 3 Elements by reverse method
rev(rev(vc1)[1:3])

[1] 77 88 99

### 2.6 Addition to Vectors

In [57]:
## Increment each element by 5

vc1 + 5
class(vc1 + 5)

[1]  15  25  35  45  55  65  75  85  95  16  27  38  49  60  71  82  93 104

[1] "numeric"

In [58]:
## Add elements of two vectors of same length

vc1 = c(10,20,30,40,50,60,70,80,90,11,22,33,44,55,66,77,88,99)
vc2 <-c(13,23,33,43,53,63,73,83,93,11,22,33,44,55,66,77,88,99)
vc1 + vc2
print(class(vc1 + vc2))

[1]  23  43  63  83 103 123 143 163 183  22  44  66  88 110 132 154 176 198

[1] "numeric"


In [59]:
## Add elements of two vectors of different length 
## ---(Warning message) ---
## After elements of shorter vector finishes, 
  # remaining elements of longer vector start getting 
  # added to start of shorter vector

vc3 <- c(13,23,33,43,53,63,73,83,93,11,22,33)
vc1 + vc3

Warning message in vc1 + vc3:
"longer object length is not a multiple of shorter object length"

[1]  23  43  63  83 103 123 143 163 183  22  44  66  57  78  99 120 141 162

In [60]:
## Add elements of two vectors of different length 
  ## but length is multiple of each other 
## --- (No Warning message) ---

vc4 <-c(13,23,33,43,53,63,73,83,93)
length(vc4)
vc1 + vc4

[1] 9

[1]  23  43  63  83 103 123 143 163 183  24  45  66  87 108 129 150 171 192

### 2.7 Built-in Functions Related to Vectors

In [61]:
print('Minimum')
min(vc1)   # Return Min of Vector
print('Maximum')
max(vc1)   # Return Max of Vector
print('Sorted Ascending Order')
sort(vc1)  # Sort a Vector
print('Sorted Descending Order')
sort(vc1, decreasing=TRUE)  # Sort a Vector, decending
print('Length')
length(vc1)   # Length of a Vector
print('Mean')
mean(vc1)     # Mean value of a Vector
print('Median')
median(vc1)   # Median value of a Vector
# If the count number of elements is even then, 
# it will calculate the mean of two middle values.
# Two middle values are determined out of sorted vectors

# Mode is not built in function (custom function is required as below)
#mode(vc1)
print('Range Function')
range(vc1)   # Returns min and Max
print('Summary Function')
summary(vc1) # Returns Min, max, 1st, median, 3rd quartiles,
print('Quantiles')
quantile(vc1, probs = c(0.25, 0.5, 0.75))  # 1st, 2nd, 3rd percentile
quantile(vc1, probs = c(0.1,0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9))  # 10th to 90th percentile
quantile(vc1)

[1] "Minimum"


[1] 10

[1] "Maximum"


[1] 99

[1] "Sorted Ascending Order"


[1] 10 11 20 22 30 33 40 44 50 55 60 66 70 77 80 88 90 99

[1] "Sorted Descending Order"


[1] 99 90 88 80 77 70 66 60 55 50 44 40 33 30 22 20 11 10

[1] "Length"


[1] 18

[1] "Mean"


[1] 52.5

[1] "Median"


[1] 52.5

[1] "Range Function"


[1] 10 99

[1] "Summary Function"


   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.00   30.75   52.50   52.50   75.25   99.00 

[1] "Quantiles"


25%   50%   75% 
30.75 52.50 75.25

10%  20%  30%  40%  50%  60%  70%  80%  90% 
17.3 25.2 33.7 43.2 52.5 61.2 69.6 78.8 88.6

0%   25%   50%   75%  100% 
10.00 30.75 52.50 75.25 99.00

### 2.8 Custom Functions Related to Vectors

In [62]:
## Mode of a Vector

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

getmode(vc1)

[1] 10

In [63]:
vec_add <- function(v1, v2){
 return (v1 + v2) 
}

vec_add(vc1 , vc2)

[1]  23  43  63  83 103 123 143 163 183  22  44  66  88 110 132 154 176 198

### 2.9 Missing values in a Vector

In [64]:
missing_vec <- c(NA, 11, 22, NA, 90, 78, NA)

length(missing_vec)  # NA will be included in length

missing_vec[4]

is.na(missing_vec)   # Return Booleans of missing Values

sum(is.na(missing_vec))  # Return count of Missing Values

[1] 7

[1] NA

[1]  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE

[1] 3

### 2.10 Reassign a value to an element in Vectors

In [65]:
temp <- c('high','high','low','medium','low', 'medium')
temp[1] <- 'very high'
temp

[1] "very high" "high"      "low"       "medium"    "low"       "medium"

### 2.11 Combine/Append multiple Vectors

In [66]:
vca = c(1,2,3)
vcb = c(4,5,6)

append(vca, vcb)

append(vca, 10)
append(vcb, 45, after=2)  # add element after position 2

[1] 1 2 3 4 5 6

[1]  1  2  3 10

[1]  4  5 45  6

### 2.12 Range of Vector

In [67]:
#--- Vector from 1 to 10 without combine --------
1:10

for (i in 1:10){
  print(i)
}

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


# 3. Factors

In [68]:
temp <- c('high','high','low','medium','low', 'medium')
temp[1] <- 'very high'
tem_factor <- factor(temp)
tem_factor

summary(tem_factor)
class(tem_factor)

[1] very high high      low       medium    low       medium   
Levels: high low medium very high

high       low    medium very high 
        1         2         2         1

[1] "factor"

# 4. Matrix

2 dimensional representation of homogeneous Data

In [69]:
# Create a 6 by 4 matrix (filled column wise)
vec <- 1:24
mat1 <- matrix(vec, nrow = 6, ncol = 4)  
mat1
summary(mat1)
class(mat1)

[,1] [,2] [,3] [,4]
[1,] 1     7   13   19  
[2,] 2     8   14   20  
[3,] 3     9   15   21  
[4,] 4    10   16   22  
[5,] 5    11   17   23  
[6,] 6    12   18   24

       V1             V2              V3              V4       
 Min.   :1.00   Min.   : 7.00   Min.   :13.00   Min.   :19.00  
 1st Qu.:2.25   1st Qu.: 8.25   1st Qu.:14.25   1st Qu.:20.25  
 Median :3.50   Median : 9.50   Median :15.50   Median :21.50  
 Mean   :3.50   Mean   : 9.50   Mean   :15.50   Mean   :21.50  
 3rd Qu.:4.75   3rd Qu.:10.75   3rd Qu.:16.75   3rd Qu.:22.75  
 Max.   :6.00   Max.   :12.00   Max.   :18.00   Max.   :24.00  

[1] "matrix"

In [70]:
# Create a 6 by 4 matrix (filled column wise)
mat3 <- matrix(vec, nrow = 6)
mat3

[,1] [,2] [,3] [,4]
[1,] 1     7   13   19  
[2,] 2     8   14   20  
[3,] 3     9   15   21  
[4,] 4    10   16   22  
[5,] 5    11   17   23  
[6,] 6    12   18   24

In [71]:
# Create a 6 by 4 matrix (filled row wise)
mat2 <- matrix(vec, nrow = 6, ncol = 4, byrow = TRUE)
mat2

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20  
[6,] 21   22   23   24

### 4.1 Indexing a Matrix

In [72]:
mat1[4,2]  # Specific element row, column
mat1[3,]   # Specific Row
mat1[,3]   # Specific Column
mat1[,]    # All matrix

[1] 10

[1]  3  9 15 21

[1] 13 14 15 16 17 18

[,1] [,2] [,3] [,4]
[1,] 1     7   13   19  
[2,] 2     8   14   20  
[3,] 3     9   15   21  
[4,] 4    10   16   22  
[5,] 5    11   17   23  
[6,] 6    12   18   24

In [73]:
mat1[3,c(2:3)]    # Row no 3, columns 2 & 3 (Output will be a Vector)
# -- OR --
mat1[3,2:3]

[1]  9 15

[1]  9 15

In [74]:
mat1[3:4,2:3]     # Row 3 & 4, columns 2 & 3 (Output will be a Matrix)

[,1] [,2]
[1,]  9   15  
[2,] 10   16

In [75]:
# Get elements from diff Row and Columns and then combine

append(mat1[3,1] ,mat1[5,4])

[1]  3 23

### 4.2 Rows, Columns and Dimensions of Matrix

In [76]:
nrow(mat1)   # Return rows
ncol(mat1)   # Return columns
dim(mat1)    # Returns rows and columns

[1] 6

[1] 4

[1] 6 4

### 4.3 Create Matrix with less elements in Vector

In [77]:
# Will give a warning message and assign first element of vector
# in the missing matrix

vc_1 = 1:23
mat4 = matrix(vc_1, nrow=6)
mat4

Warning message in matrix(vc_1, nrow = 6):
"data length [23] is not a sub-multiple or multiple of the number of rows [6]"

[,1] [,2] [,3] [,4]
[1,] 1     7   13   19  
[2,] 2     8   14   20  
[3,] 3     9   15   21  
[4,] 4    10   16   22  
[5,] 5    11   17   23  
[6,] 6    12   18    1

# 5. Arrays

In [78]:
vc <- 1:24
arr <- array(vc, dim = c(4,3,2))   # Create TWO 4x3 Matrices
print(arr)
dim(arr)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



[1] 4 3 2

### 5.1 Indexing Array

In [79]:
arr[4,3,2]   # Get 4th Row, 3rd Column in 2nd Matrix
arr[,,2]     # Get 2nd Matrix

[1] 24

[,1] [,2] [,3]
[1,] 13   17   21  
[2,] 14   18   22  
[3,] 15   19   23  
[4,] 16   20   24

# 6. Lists

- Lists are one dimensional representation of Heterogeneous Data
- Every element is represented as a single item vector
- Due to this list can hold any data type

In [80]:
ls1 <- list(1,3,7, 'char', TRUE, 'chart', FALSE, 'test')
print(ls1)
class(ls1)

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 7

[[4]]
[1] "char"

[[5]]
[1] TRUE

[[6]]
[1] "chart"

[[7]]
[1] FALSE

[[8]]
[1] "test"



[1] "list"

In [81]:
ls2 <- list(1,2,3,45)
ls2

ls3 <- list(34, 'char', vc_1, mat1)
ls3

class(ls3[3])
class(ls3[[3]])
ls3[[3]]

ls3[[4]]

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 45

[[1]]
[1] 34

[[2]]
[1] "char"

[[3]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23

[[4]]
     [,1] [,2] [,3] [,4]
[1,]    1    7   13   19
[2,]    2    8   14   20
[3,]    3    9   15   21
[4,]    4   10   16   22
[5,]    5   11   17   23
[6,]    6   12   18   24

[1] "list"

[1] "integer"

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23

[,1] [,2] [,3] [,4]
[1,] 1     7   13   19  
[2,] 2     8   14   20  
[3,] 3     9   15   21  
[4,] 4    10   16   22  
[5,] 5    11   17   23  
[6,] 6    12   18   24

### 6.1 Nested / Recursive Lists
- List within a list

In [82]:
ls4 = list(34, TRUE, ls1)
ls4

[[1]]
[1] 34

[[2]]
[1] TRUE

[[3]]
[[3]][[1]]
[1] 1

[[3]][[2]]
[1] 3

[[3]][[3]]
[1] 7

[[3]][[4]]
[1] "char"

[[3]][[5]]
[1] TRUE

[[3]][[6]]
[1] "chart"

[[3]][[7]]
[1] FALSE

[[3]][[8]]
[1] "test"

# 7. Apply Functions

In [86]:
m <- matrix(1:12, 3, 4)
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

### 7.1 Apply

In [48]:
apply(m, 1, sum)  # Row wise sum
apply(m, 2, sum)  # Column wise sum
sum(m)  # sum of all elements in matrix

[1] 22 26 30

[1]  6 15 24 33

[1] 78

### 7.2 L Apply

In [49]:
## Lapply--returns a list
a <- 1:3 
b <- 4:6
c <- 7:9
ls <- list(a,b,c)
ls

lapply(ls, sum)
class(lapply(ls, sum))

lapply(ls, range)

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

[[3]]
[1] 7 8 9

[[1]]
[1] 6

[[2]]
[1] 15

[[3]]
[1] 24

[1] "list"

[[1]]
[1] 1 3

[[2]]
[1] 4 6

[[3]]
[1] 7 9

### 7.3 S Apply

In [50]:
## Sapply--returns a vector or a Matrix

sapply(ls, sum)
class(sapply(ls, sum))

sapply(ls, range)
class(sapply(ls, range))

[1]  6 15 24

[1] "integer"

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 3    6    9

[1] "matrix"

# 8. Assignment

###  8.1 Create a Matrix and Assign Column and Row Names instead of 1,2,3 ... etc

In [87]:
m <- matrix(1:12, 3, 4)
m
dimnames(m) <- list(c('row1','row2','row3'), c('col1', 'col2', 'col3', 'col4'))
m
dimnames(m) <- list(month.abb[1:3], month.abb[4:7])
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

col1 col2 col3 col4
row1 1    4    7    10  
row2 2    5    8    11  
row3 3    6    9    12

Apr May Jun Jul
Jan 1   4   7   10 
Feb 2   5   8   11 
Mar 3   6   9   12

### 8.2 Check if a vector is recursive in Nature (nested vector)

- No

In [52]:
vc1
vc2
vc_r = c(vc1, vc2)
vc_r

[1] 10 20 30 40 50 60 70 80 90 11 22 33 44 55 66 77 88 99

[1] 13 23 33 43 53 63 73 83 93 11 22 33 44 55 66 77 88 99

[1] 10 20 30 40 50 60 70 80 90 11 22 33 44 55 66 77 88 99 13 23 33 43 53 63 73
[26] 83 93 11 22 33 44 55 66 77 88 99